USE [DYNAMICS]
GO

/****** Object:  Table [dbo].[WEBCOMPANY_VOG]    Script Date: 14/07/2023 14:13:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WEBCOMPANY_VOG](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[INTERID] [nchar](5) NOT NULL,
	[CRTUSER] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_WEBCOMPANY_VOG] PRIMARY KEY CLUSTERED 
(
	[INTERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DYNAMICS]
GO

/****** Object:  Table [dbo].[WEBUSERS_VOG]    Script Date: 14/07/2023 14:18:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--drop table [WEBUSERS_VOG]
CREATE TABLE [dbo].[WEBUSERS_VOG](
	[ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[USUARIO] [nvarchar](15) NOT NULL,
	[PASSWORD] [nvarchar](500) NOT NULL,
	[IDPERFIL] [int] NOT NULL,
	[NOMBREUSUARIO] [varchar](100) NULL,
	[ESTATUS] [int] NULL,
	flg_CAMBIOCLAVE BIT
 CONSTRAINT [PK_WEBUSERS_VOG] PRIMARY KEY CLUSTERED 
(
	[USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

